[package]
name = "chip8"
version = "0.1.0"
edition = "2024"
categories = ["no-std"]

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
fastrand = "2.3.0"
itertools = "0.14.0"
ratatui = "0.29.0"


[[bin]]
name = "chip8"
